[package]
name = "rustracer"
version = "0.1.0"
authors = ["Michael Kwok <michael.kwok00@gmail.com>"]
edition = "2018"

[profile.release]
debug = true

[dependencies]
num = "^0.3.0"
rand = "^0.7.3"
rayon = "^1.3.1"
