[package]
name = "rustracer"
version = "0.1.0"
authors = ["Michael Kwok <michael.kwok00@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "^0.3.0"
rand = "^0.7.3"